export const ideaService = {
  getSeedData: (userId) => [
    {
      id: 'idea-1',
      title: 'AI-Powered Personal Finance Advisor',
      problem: 'Many people struggle to manage their daily expenses and savings effectively due to a lack of financial literacy and time.',
      solution: 'An AI-driven mobile app that categorizes expenses automatically and provides personalized saving tips based on spending habits.',
      technologies: 'React Native, Node.js, TensorFlow Lite, Python',
      impact: 'Helps users achieve financial stability and reduce unnecessary debt.',
      contact_email: 'finance-ai@example.com',
      contact_phone: '+1-555-0101',
      user_id: userId
    },
    {
      id: 'idea-2',
      title: 'Decentralized Peer-to-Peer Energy Trading',
      problem: 'Solar panel owners often have excess energy that goes to waste or is sold to grids at very low rates.',
      solution: 'A blockchain platform that allows neighbors to buy and sell excess renewable energy directly using smart contracts.',
      technologies: 'Ethereum, Solidity, Web3.js, React',
      impact: 'Promotes renewable energy usage and reduces electricity costs for communities.',
      contact_email: 'energy-trade@example.com',
      contact_phone: '+1-555-0102',
      user_id: userId
    },
    {
      id: 'idea-3',
      title: 'Smart Agriculture Irrigation System',
      problem: 'Water wastage in agriculture due to inefficient irrigation methods and unpredictable weather.',
      solution: 'IoT sensors that monitor soil moisture and weather forecasts to automate irrigation through a centralized dashboard.',
      technologies: 'Arduino, LoRaWAN, Node.js, MQTT',
      impact: 'Reduces water consumption by up to 40% and increases crop yields.',
      contact_email: 'agri-smart@example.com',
      contact_phone: '+1-555-0103',
      user_id: userId
    },
    {
      id: 'idea-4',
      title: 'Blockchain-Based Supply Chain Transparency',
      problem: 'Counterfeit products and lack of ethical sourcing data in global supply chains.',
      solution: 'A distributed ledger system where every step of a product\'s journey is recorded and verifiable via QR codes.',
      technologies: 'Hyperledger Fabric, Go, React, Docker',
      impact: 'Increases consumer trust and ensures fair labor practices.',
      contact_email: 'supply-chain@example.com',
      contact_phone: '+1-555-0104',
      user_id: userId
    },
    {
      id: 'idea-5',
      title: 'VR-Based Mental Health Therapy',
      problem: 'Traditional therapy can be expensive and inaccessible for those with phobias or severe social anxiety.',
      solution: 'Immersive VR environments that simulate controlled exposure therapy and provide relaxation modules led by AI guides.',
      technologies: 'Unity3D, C#, Meta Quest SDK, NLP',
      impact: 'Provides a safe and scalable way to treat anxiety and PTSD.',
      contact_email: 'vr-therapy@example.com',
      contact_phone: '+1-555-0105',
      user_id: userId
    },
    {
      id: 'idea-6',
      title: 'E-Waste Recycling Reward Platform',
      problem: 'Low recycling rates for electronic waste leading to environmental contamination.',
      solution: 'An app that connects users with recycling centers and rewards them with tokens or discounts for dropping off gadgets.',
      technologies: 'Flutter, Firebase, Stripe API',
      impact: 'Reduces landfill waste and recovers precious metals efficiently.',
      contact_email: 'recycle-app@example.com',
      contact_phone: '+1-555-0106',
      user_id: userId
    },
    {
      id: 'idea-7',
      title: 'AI Translation for Rare Dialects',
      problem: 'Low-resource languages and regional dialects are often ignored by major translation services.',
      solution: 'A crowdsourced platform where native speakers provide training data for a transformer-based translation model.',
      technologies: 'PyTorch, Hugging Face, React, FastAPI',
      impact: 'Preserves cultural heritage and improves global communication.',
      contact_email: 'dialect-ai@example.com',
      contact_phone: '+1-555-0107',
      user_id: userId
    },
    {
      id: 'idea-8',
      title: 'Contactless Smart Parking App',
      problem: 'Drivers waste time and fuel searching for parking in congested city centers.',
      solution: 'Real-time sensor-based parking spot detection and automated payment via license plate recognition.',
      technologies: 'Raspberry Pi, OpenCV, Node.js, AWS IoT',
      impact: 'Reduces urban traffic and carbon emissions.',
      contact_email: 'parking-smart@example.com',
      contact_phone: '+1-555-0108',
      user_id: userId
    },
    {
      id: 'idea-9',
      title: 'Community-Driven Micro-Lending Platform',
      problem: 'Small business owners in developing regions often lack access to traditional bank loans.',
      solution: 'A crowdfunding micro-loan platform where individuals can lend small amounts with zero interest or low fixed rates.',
      technologies: 'React, Spring Boot, PostgreSQL, Plaid',
      impact: 'Empowers local entrepreneurs and boosts local economies.',
      contact_email: 'micro-lend@example.com',
      contact_phone: '+1-555-0109',
      user_id: userId
    },
    {
      id: 'idea-10',
      title: 'Automated Food Waste Management for Restaurants',
      problem: 'Restaurants discard massive amounts of perfectly edible food due to over-ordering and short shelf lives.',
      solution: 'An inventory tracking system that predicts food demand using ML and suggests recipes for near-expiry ingredients.',
      technologies: 'Next.js, Python, Scikit-learn, PostgreSQL',
      impact: 'Reduces operational costs and global food waste.',
      contact_email: 'food-waste@example.com',
      contact_phone: '+1-555-0110',
      user_id: userId
    },
    {
      id: 'idea-11',
      title: 'Telemedicine for Remote Rural Areas',
      problem: 'Lack of medical specialists in remote villages leads to delayed diagnoses and high mortality.',
      solution: 'A low-bandwidth video conferencing app with integrated diagnostic assistant for local health workers.',
      technologies: 'WebRTC, React, Node.js, MongoDB',
      impact: 'Saves lives by providing expert medical advice to underserved populations.',
      contact_email: 'rural-med@example.com',
      contact_phone: '+1-555-0111',
      user_id: userId
    },
    {
      id: 'idea-12',
      title: 'Smart Home Energy Management Hub',
      problem: 'Difficulty in monitoring and controlling individual appliance power consumption.',
      solution: 'A centralized IoT hub that identifies power-hungry devices and suggests schedule optimizations to lower bills.',
      technologies: 'Home Assistant, Zigbee, Python, InfluxDB',
      impact: 'Encourages energy conservation and lowers household expenses.',
      contact_email: 'energy-hub@example.com',
      contact_phone: '+1-555-0112',
      user_id: userId
    },
    {
      id: 'idea-13',
      title: 'AI Proctoring for Online Examinations',
      problem: 'Maintaining academic integrity in remote exams is challenging and prone to manual error.',
      solution: 'A browser-based AI tool that detects suspicious behavior, multi-person presence, and unauthorized device usage via webcam.',
      technologies: 'TensorFlow.js, MediaPipe, React, WebAssembly',
      impact: 'Enables fair and scalable remote education.',
      contact_email: 'ai-proctor@example.com',
      contact_phone: '+1-555-0113',
      user_id: userId
    },
    {
      id: 'idea-14',
      title: 'Crowdsourced Urban Infrastructure Reporter',
      problem: 'Potholes, broken streetlights, and leaking pipes often go unreported for weeks.',
      solution: 'A location-based app where residents can snap photos of issues and automatically alert municipal authorities.',
      technologies: 'Google Maps API, Flutter, Firebase',
      impact: 'Speeds up urban maintenance and improves city safety.',
      contact_email: 'city-reporter@example.com',
      contact_phone: '+1-555-0114',
      user_id: userId
    },
    {
      id: 'idea-15',
      title: 'Personalized Adaptive Learning Platform',
      problem: 'One-size-fits-all education fails to account for different student learning speeds and styles.',
      solution: 'An AI-driven LMS that adjusts course difficulty and content medium (video/text/quiz) based on real-time performance.',
      technologies: 'Next.js, Python, Django, OpenAI API',
      impact: 'Improves student engagement and knowledge retention rates.',
      contact_email: 'adaptive-learn@example.com',
      contact_phone: '+1-555-0115',
      user_id: userId
    },
    {
      id: 'idea-16',
      title: 'Smart Helmet for Industrial Workers',
      problem: 'High rates of accidents in construction and mining due to hazardous gas or falls.',
      solution: 'A safety helmet equipped with gas sensors, impact detection, and GPS for emergency worker tracking.',
      technologies: 'ESP32, LoRa, Node.js, Grafana',
      impact: 'Significantly enhances workplace safety and emergency response.',
      contact_email: 'safety-helmet@example.com',
      contact_phone: '+1-555-0116',
      user_id: userId
    },
    {
      id: 'idea-17',
      title: 'AI Interior Designer for Small Spaces',
      problem: 'Urban residents struggle to furnish tiny apartments efficiently and aesthetically.',
      solution: 'An AR app that scans a room and generates 3D layout recommendations based on furniture inventory and user style.',
      technologies: 'ARCore, Unity3D, Three.js, Stable Diffusion',
      impact: 'Makes professional-quality interior design accessible to everyone.',
      contact_email: 'interior-ai@example.com',
      contact_phone: '+1-555-0117',
      user_id: userId
    },
    {
      id: 'idea-18',
      title: 'Privacy-First Data Marketplace',
      problem: 'Large corporations monetize user data without fair compensation or transparency.',
      solution: 'A blockchain marketplace where users can choose to share anonymized data in exchange for direct payments.',
      technologies: 'Polygon, Solidity, Node.js, React',
      impact: 'Gives users ownership over their digital identity and monetization.',
      contact_email: 'data-market@example.com',
      contact_phone: '+1-555-0118',
      user_id: userId
    },
    {
      id: 'idea-19',
      title: 'Intelligent Crop Disease Diagnostic App',
      problem: 'Farmers lose significant portions of their crops to pests and diseases due to slow diagnosis.',
      solution: 'A mobile app where farmers upload photos of leaf damage and receive instant diagnosis and treatment advice via AI.',
      technologies: 'Flutter, PyTorch Mobile, FastAPI',
      impact: 'Prevents large-scale crop failure and secures food supplies.',
      contact_email: 'crop-diag@example.com',
      contact_phone: '+1-555-0119',
      user_id: userId
    },
    {
      id: 'idea-20',
      title: 'Dynamic Ride-Sharing for Corporate Commuters',
      problem: 'Traffic congestion and high commuting costs for employees working in busy industrial parks.',
      solution: 'A dedicated ride-sharing app that matches employees from the same or nearby companies to share commutes.',
      technologies: 'React Native, Node.js, MongoDB, Redis',
      impact: 'Reduces commute stress and collective environmental footprint.',
      contact_email: 'corp-ride@example.com',
      contact_phone: '+1-555-0120',
      user_id: userId
    },
    {
      id: 'idea-21',
      title: 'Real-time Deepfake Detection Plugin',
      problem: 'Spreading of misinformation through highly convincing AI-generated video and audio content.',
      solution: 'A browser extension that analyzes media streams in real-time to flag potential synthetic manipulations.',
      technologies: 'JavaScript, WebAssembly, Python, OpenCV',
      impact: 'Combats digital misinformation and protects public figures.',
      contact_email: 'deepfake-detect@example.com',
      contact_phone: '+1-555-0121',
      user_id: userId
    },
    {
      id: 'idea-22',
      title: 'Smart Warehouse Drone Inventory Scout',
      problem: 'Manual inventory counting in large warehouses is time-consuming, expensive, and dangerous.',
      solution: 'Autonomous drones that fly through warehouse aisles scanning RFID tags and barcodes to update the central database.',
      technologies: 'ROS, Python, OpenCV, MQTT',
      impact: 'Increases inventory accuracy and lowers logistics overhead.',
      contact_email: 'warehouse-drone@example.com',
      contact_phone: '+1-555-0122',
      user_id: userId
    },
    {
      id: 'idea-23',
      title: 'Gamified Fitness App for Seniors',
      problem: 'Lack of motivation and specialized physical routines for elderly individuals.',
      solution: 'An app with gentle motion-sensing exercises integrated with 3D story-driven games and community features.',
      technologies: 'Unity, C#, Mobile Accelerometer',
      impact: 'Improves physical health and social connectivity for seniors.',
      contact_email: 'senior-fit@example.com',
      contact_phone: '+1-555-0123',
      user_id: userId
    },
    {
      id: 'idea-24',
      title: 'AI-Enhanced Legal Document Reviewer',
      problem: 'Contract review is a bottleneck for startups and small law firms due to the volume of legal jargon.',
      solution: 'A tool that highlights risky clauses and summarizes key obligations in standard business contracts using NLP.',
      technologies: 'Python, BERT, React, PostgreSQL',
      impact: 'Lowers legal fees and speeds up business negotiations.',
      contact_email: 'legal-reviewer@example.com',
      contact_phone: '+1-555-0124',
      user_id: userId
    },
    {
      id: 'idea-25',
      title: 'Ocean Plastic Tracking System',
      problem: 'Difficulty in locating and predicting the path of large plastic debris patches in the ocean.',
      solution: 'Satellite imagery analysis combined with ocean current models to direct cleanup vessels effectively.',
      technologies: 'Python, Google Earth Engine, XGBoost',
      impact: 'Enables targeted and efficient ocean restoration efforts.',
      contact_email: 'ocean-plastic@example.com',
      contact_phone: '+1-555-0125',
      user_id: userId
    },
    {
      id: 'idea-26',
      title: 'Voice-Activated Shopping Assistant for Visually Impaired',
      problem: 'Navigating grocery stores and identifying products is extremely difficult for the blind.',
      solution: 'A wearable device or app that reads labels and prices aloud and provides turn-by-turn indoor navigation.',
      technologies: 'Raspberry Pi, Python, OCR, TTS',
      impact: 'Promotes independence and accessibility in daily life.',
      contact_email: 'voice-shop@example.com',
      contact_phone: '+1-555-0126',
      user_id: userId
    },
    {
      id: 'idea-27',
      title: 'Smart Disaster Response Logistics',
      problem: 'Coordinating various NGOs and aid providers during natural disasters is chaotic and slow.',
      solution: 'A real-time hub that maps aid requirements against available resources to prevent duplication and gaps.',
      technologies: 'React, Node.js, Leaflet, Socket.io',
      impact: 'Ensures efficient help reaches those in transition quicker.',
      contact_email: 'disaster-hub@example.com',
      contact_phone: '+1-555-0127',
      user_id: userId
    },
    {
      id: 'idea-28',
      title: 'Zero-Waste Fashion Marketplace',
      problem: 'Fast fashion contributes heavily to textile waste and carbon emissions.',
      solution: 'A resale and upcycling platform where users trade clothes and buy items reworked by local designers.',
      technologies: 'Next.js, Firebase, Algolia',
      impact: 'Encourages sustainable consumption and supports local creatives.',
      contact_email: 'zero-fashion@example.com',
      contact_phone: '+1-555-0128',
      user_id: userId
    },
    {
      id: 'idea-29',
      title: 'AI Tutor for High School Physics',
      problem: 'Physics concepts like electromagnetism and quantum mechanics are hard to visualize and master alone.',
      solution: 'An interactive tutor that uses simulations and step-by-step Socratic questioning to solve complex problems.',
      technologies: 'React, Canvas API, Python, LLama 3',
      impact: 'Boosts confidence and academic performance in STEM subjects.',
      contact_email: 'physics-tutor@example.com',
      contact_phone: '+1-555-0129',
      user_id: userId
    },
    {
      id: 'idea-30',
      title: 'Automated Carbon Footprint Calculator for SMEs',
      problem: 'Small businesses find it too complex and costly to audit their environmental impact.',
      solution: 'A dashboard that integrates with accounting software to calculate carbon impact based on supply and logistics data.',
      technologies: 'Spring Boot, React, Python, AWS Lambda',
      impact: 'Helps small businesses transition to green operations sustainably.',
      contact_email: 'carbon-calc@example.com',
      contact_phone: '+1-555-0130',
      user_id: userId
    },
    {
      id: 'idea-31',
      title: 'Hyperlocal Volunteer Matching Service',
      problem: 'Many people want to help locally but don\'t know where their specific skills are most needed.',
      solution: 'An app that matches volunteers to nearby neighborhood projects based on availability and verified skills.',
      technologies: 'Flutter, Firebase, GeoFirestore',
      impact: 'Strengthens community bonds and social impact efficiency.',
      contact_email: 'volunteer-match@example.com',
      contact_phone: '+1-555-0131',
      user_id: userId
    }
  ]
};
