export const jobService = {
  getSeedData: () => [
    {
      id: 'job-1',
      title: 'Full Stack Developer Intern',
      company: 'Google',
      location: 'Mountain View, CA / Remote',
      salary: '$45 - $60 / hr',
      sector: 'Technology',
      role: 'Full Stack Developer',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'React, Node.js, TypeScript, Cloud Functions',
      description: 'Work with the Gemini team to build next-generation AI interfaces. You will be responsible for developing responsive frontend components and scalable backend microservices.',
      link: 'https://www.google.com/about/careers/applications/jobs/results/intern-2025',
      deadline: Date.now() + 30 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-2',
      title: 'Generative AI Engineer',
      company: 'OpenAI',
      location: 'San Francisco, CA',
      salary: '$180k - $250k',
      sector: 'Artificial Intelligence',
      role: 'Generative AI Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'PG',
      required_skills: 'Python, PyTorch, LLMs, Transformer Architectures',
      description: 'Join the team pushing the boundaries of what AI can do. Develop and optimize large-scale language models and integrate them into production APIs.',
      link: 'https://openai.com/careers/engineer-gen-ai',
      deadline: Date.now() + 45 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-3',
      title: 'Software Development Engineer I',
      company: 'Amazon',
      location: 'Seattle, WA',
      salary: '$130k - $160k',
      sector: 'Technology / E-commerce',
      role: 'Software Development Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Java, AWS, Distributed Systems, DynamoDB',
      description: 'Impact millions of customers globally by building highly available services for the Amazon retail platform.',
      link: 'https://www.amazon.jobs/en/jobs/2544321',
      deadline: Date.now() + 20 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-4',
      title: 'Cybersecurity Analyst',
      company: 'Microsoft',
      location: 'Redmond, WA / Remote',
      salary: '$110k - $145k',
      sector: 'Technology / Security',
      role: 'Cybersecurity Analyst',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Sentinel, Azure Security, Python, Threat Hunting',
      description: 'Protect the Microsoft ecosystem by detecting and neutralizing advanced persistent threats in cloud environments.',
      link: 'https://careers.microsoft.com/us/en/job/security-analyst-2025',
      deadline: Date.now() + 15 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-5',
      title: 'Data Science Intern',
      company: 'Meta',
      location: 'Menlo Park, CA',
      salary: '$8000 / month',
      sector: 'Social Media / Big Data',
      role: 'Data Scientist',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'SQL, R, Python, Stats, Product Analytics',
      description: 'Analyze user behavior data to drive product decisions for Instagram and WhatsApp.',
      link: 'https://www.metacareers.com/jobs/data-intern-2025',
      deadline: Date.now() + 60 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-6',
      title: 'Backend Engineer (Intern)',
      company: 'Netflix',
      location: 'Los Gatos, CA',
      salary: '$50 / hr',
      sector: 'Entertainment / Media',
      role: 'Backend Engineer',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Java, Spring Boot, Microservices, Cassandra',
      description: 'Optimize the edge services that power Netflix streaming for over 200 million members.',
      link: 'https://jobs.netflix.com/jobs/intern-backend-2025',
      deadline: Date.now() + 35 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-7',
      title: 'AI Research Scientist',
      company: 'DeepMind',
      location: 'London, UK',
      salary: '£90k - £130k',
      sector: 'Artificial Intelligence / Research',
      role: 'AI Research Scientist',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'PG',
      required_skills: 'Jax, TensorFlow, Reinforcement Learning, Research Design',
      description: 'Solve intelligence by developing agents capable of learning complex tasks in diverse environments.',
      link: 'https://deepmind.google/careers/research-scientist',
      deadline: Date.now() + 50 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-8',
      title: 'Frontend Engineer',
      company: 'Airbnb',
      location: 'Remote, US',
      salary: '$150k - $190k',
      sector: 'Travel / Hospitality',
      role: 'Frontend Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'React, GraphQL, CSS-in-JS, Performance Optimization',
      description: 'Build beautiful, inclusive, and performant web interfaces for the global travel community.',
      link: 'https://careers.airbnb.com/positions/frontend-eng',
      deadline: Date.now() + 25 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-9',
      title: 'Blockchain Developer',
      company: 'Coinbase',
      location: 'Remote',
      salary: '$160k - $210k',
      sector: 'Finance / Web3',
      role: 'Blockchain Developer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Solidity, Rust, Ethereum, Cryptography',
      description: 'Develop secure and scalable smart contracts and infrastructure for the future of decentralized finance.',
      link: 'https://www.coinbase.com/careers/positions/blockchain-dev',
      deadline: Date.now() + 40 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-10',
      title: 'Machine Learning Intern',
      company: 'Tesla',
      location: 'Palo Alto, CA',
      salary: '$40 - $55 / hr',
      sector: 'Automotive / AI',
      role: 'Machine Learning Engineer',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Python, C++, PyTorch, Computer Vision',
      description: 'Contribute to the Autopilot and Full Self-Driving AI stack. Work on vision-based perception and control.',
      link: 'https://www.tesla.com/careers/job/intern-ml-vision',
      deadline: Date.now() + 10 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-11',
      title: 'Graduate Engineer Trainee',
      company: 'ISRO',
      location: 'Bengaluru, India',
      salary: '₹6L - ₹8L PA',
      sector: 'Aerospace / Government',
      role: 'Graduate Engineer Trainee',
      type: 'Full-time',
      category: 'Government',
      min_qualification: 'UG',
      required_skills: 'Aerospace Engineering, Physics, MATLAB, C',
      description: 'Participate in satellite launch vehicle design and payload integration for future space missions.',
      link: 'https://www.isro.gov.in/careers',
      deadline: Date.now() + 55 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-12',
      title: 'Cloud Solutions Architect',
      company: 'Oracle',
      location: 'Austin, TX',
      salary: '$140k - $180k',
      sector: 'Technology / Cloud',
      role: 'Cloud Solutions Architect',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'OCI, Terraform, Kubernetes, Networking',
      description: 'Design and implement complex cloud architectures for enterprise customers migrating to Oracle Cloud Infrastructure.',
      link: 'https://eeho.fa.us2.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1/job/12345',
      deadline: Date.now() + 30 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-13',
      title: 'DevOps Engineer Intern',
      company: 'Spotify',
      location: 'Stockholm, Sweden / Remote',
      salary: 'Competitive',
      sector: 'Media / Streaming',
      role: 'DevOps Engineer',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Docker, Kubernetes, Jenkins, Python, GCP',
      description: 'Support the developer productivity teams by automating CI/CD pipelines and improving platform reliability.',
      link: 'https://www.lifeatspotify.com/jobs/devops-intern-2025',
      deadline: Date.now() + 20 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-14',
      title: 'Senior Product Designer',
      company: 'Slack',
      location: 'Remote, US',
      salary: '$170k - $220k',
      sector: 'Technology / Communication',
      role: 'Product Designer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Figma, Design Systems, UX Research, Prototyping',
      description: 'Design the future of teamwork. Create intuitive experiences that make work life simpler, more pleasant, and more productive.',
      link: 'https://slack.com/careers/product-designer',
      deadline: Date.now() + 50 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-15',
      title: 'Quantitative Trading Intern',
      company: 'Jane Street',
      location: 'New York, NY',
      salary: '$20,000 / month',
      sector: 'Finance / Trading',
      role: 'Quantitative Trader',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'OCaml, Advanced Probability, Game Theory, C++',
      description: 'Work on the trading floor, developing and testing models to price and trade complex financial instruments.',
      link: 'https://www.janestreet.com/join-jane-street/position/internships/',
      deadline: Date.now() + 15 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-16',
      title: 'Embedded Systems Engineer',
      company: 'NVIDIA',
      location: 'Santa Clara, CA',
      salary: '$155k - $205k',
      sector: 'Semiconductors / AI',
      role: 'Embedded Systems Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'C, Linux Kernel, RTOS, ARM Architecture',
      description: 'Develop low-level software and drivers for the next generation of autonomous vehicle hardware.',
      link: 'https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/Embedded-Engineer',
      deadline: Date.now() + 25 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-17',
      title: 'Mobile App Developer (iOS)',
      company: 'Apple',
      location: 'Cupertino, CA',
      salary: '$145k - $185k',
      sector: 'Consumer Electronics',
      role: 'Mobile Developer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Swift, SwiftUI, Combine, App Kit',
      description: 'Create high-performance iOS applications that define the standard for design and functionality on the App Store.',
      link: 'https://jobs.apple.com/en-us/details/200543210',
      deadline: Date.now() + 45 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-18',
      title: 'Security Researcher',
      company: 'Palantir',
      location: 'London, UK / DC, USA',
      salary: '$120k - $170k',
      sector: 'Technology / Intelligence',
      role: 'Security Researcher',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Reverse Engineering, Vulnerability Research, x86/ARM',
      description: 'Conduct deep security audits of internal and external software stacks to find and fix zero-day vulnerabilities.',
      link: 'https://www.palantir.com/careers/security-researcher',
      deadline: Date.now() + 30 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-19',
      title: 'Site Reliability Engineer',
      company: 'Twitter (X)',
      location: 'San Francisco, CA',
      salary: '$160k - $220k',
      sector: 'Social Media / Infrastructure',
      role: 'Site Reliability Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Linux, Go, Python, Distributed Systems, Incident Response',
      description: 'Keep the town square of the internet running. Manage global scale infrastructure with code.',
      link: 'https://careers.twitter.com/en/work-at-twitter/sre-engineering',
      deadline: Date.now() + 10 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-20',
      title: 'AR/VR Software Intern',
      company: 'Snap Inc.',
      location: 'Santa Monica, CA',
      salary: '$55 / hr',
      sector: 'Media / Augmented Reality',
      role: 'AR/VR Developer',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Lens Studio, C++, Graphics Programming, Unity',
      description: 'Help build the next generation of augmented reality experiences for millions of Snapchat users.',
      link: 'https://www.snap.com/en-US/jobs/ar-intern-2025',
      deadline: Date.now() + 60 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-21',
      title: 'Software Engineer - Scientific Computing',
      company: 'SpaceX',
      location: 'Hawthorne, CA',
      salary: '$120k - $170k',
      sector: 'Aerospace / Tech',
      role: 'Software Engineer',
      type: 'Full-time',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'C++, Python, Numerical Analysis, Thermodynamics',
      description: 'Write the simulation software used to design Starship and Falcon rockets.',
      link: 'https://www.spacex.com/careers/scientific-software-engineer',
      deadline: Date.now() + 35 * 24 * 60 * 60 * 1000
    },
    {
      id: 'job-22',
      title: 'Government Tech Consultant (Intern)',
      company: 'Deloitte',
      location: 'Washington DC / Hybrid',
      salary: '$35 / hr',
      sector: 'Consulting / Government',
      role: 'Tech Consultant',
      type: 'Internship',
      category: 'Private',
      min_qualification: 'UG',
      required_skills: 'Azure, SQL, Documentation, Business Analyst',
      description: 'Help government agencies modernize their IT infrastructure and adopt cloud-first strategies.',
      link: 'https://jobs2.deloitte.com/us/en/job/intern-gov-tech',
      deadline: Date.now() + 40 * 24 * 60 * 60 * 1000
    }
  ]
};
