import React, { useState } from 'react';
import { Upload, FileText, CheckCircle, Loader2, RefreshCw, ChevronRight, Briefcase, Lightbulb, X, AlertCircle } from 'lucide-react';
import { User, ResumeAnalysis } from '../types';
import { apiService } from '../services/apiService';

interface ResumeAnalyzerProps {
  user: User;
  onBack: () => void;
}

export const ResumeAnalyzer: React.FC<ResumeAnalyzerProps> = ({ user, onBack }) => {
  const [state, setState] = useState<'IDLE' | 'ANALYZING' | 'RESULT'>('IDLE');
  const [progress, setProgress] = useState(0);
  const [analysisStep, setAnalysisStep] = useState("Initializing...");
  const [file, setFile] = useState<File | null>(null);
  const [analysis, setAnalysis] = useState<ResumeAnalysis | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [jobDescription, setJobDescription] = useState("");

  const handleFileUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const selectedFile = e.target.files[0];
      setFile(selectedFile);
      startAnalysis(selectedFile);
    }
  };

  const startAnalysis = async (fileToAnalyze: File) => {
    setState('ANALYZING');
    setProgress(10);
    setError(null);
    setAnalysisStep("Uploading and Scanning...");

    try {
      const formData = new FormData();
      formData.append("resume", fileToAnalyze);
      if (jobDescription.trim()) {
        formData.append("jobDescription", jobDescription.trim());
      }

      const progressInterval = setInterval(() => {
        setProgress(prev => {
          if (prev >= 90) return prev;
          return prev + 5;
        });
        setAnalysisStep(prev => prev === "Scanning..." ? "Analyzing Content..." : "Scanning...");
      }, 800);

      const result = await apiService.analyzeResume(formData);
      
      clearInterval(progressInterval);
      setProgress(100);
      setAnalysisStep("Finalizing Report...");

      setTimeout(() => {
        setAnalysis(result);
        setState('RESULT');
      }, 500);

    } catch (err: any) {
      console.error("Resume analysis error:", err);
      setError(err.message || "Analysis failed. Please try again.");
      setState('IDLE');
    }
  };

  const getScoreColor = (s: number) => {
    if (s >= 80) return "text-emerald-500 border-emerald-500/30 bg-emerald-500/10";
    if (s >= 60) return "text-yellow-500 border-yellow-500/30 bg-yellow-500/10";
    return "text-red-500 border-red-500/30 bg-red-500/10";
  };

  const getScoreGrade = (s: number) => {
    if (s >= 80) return "Great";
    if (s >= 60) return "Good";
    return "Needs Improvement";
  };

  const handleDownload = () => {
    if (!analysis) return;
    const reportTitle = `SkillVouch ATS Engine v1.0 - Audit Report - ${file?.name || 'Candidate'}`;
    const reportContent = `
${reportTitle}
==========================================
Date: ${new Date().toLocaleDateString()}
Final ATS Score: ${analysis.ats_score}/100
Grade: ${getScoreGrade(analysis.ats_score)}

Metric Breakdown:
- Keyword Match (35%): ${analysis.keyword_match_score}/35
- Skills Coverage (20%): ${analysis.skills_score}/20
- Work Experience (20%): ${analysis.experience_score}/20
- Education & Certs (10%): ${analysis.education_score}/10
- Formatting & Compat (15%): ${analysis.formatting_score}/15

Critical Gaps (Missing Keywords):
${analysis.missing_keywords.length > 0 ? analysis.missing_keywords.map(kw => `- ${kw}`).join('\n') : "No critical keywords missing."}

Weak Resume Sections:
${analysis.weak_sections.length > 0 ? analysis.weak_sections.map(s => `- ${s}`).join('\n') : "Structure health is optimal."}

Formatting Violations:
${analysis.formatting_issues.length > 0 ? analysis.formatting_issues.map(i => `- ${i}`).join('\n') : "Formatting is ATS-compatible."}

Actionable Suggestions:
${analysis.suggestions.length > 0 ? analysis.suggestions.map(s => `- ${s}`).join('\n') : "No major optimization tips."}

Improved Bullet Point Examples:
${analysis.improved_bullet_points.length > 0 ? analysis.improved_bullet_points.map(bp => `- ${bp}`).join('\n') : "Bullet points are strong."}

Generated by SkillVouch ATS Engine v1.0
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ATS_Audit_V1_${file?.name.split('.')[0] || 'Report'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="max-w-6xl mx-auto p-4 md:p-8 space-y-8 animate-fade-in">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-indigo-500/20 rounded-xl text-indigo-500 border border-indigo-500/30 shadow-lg shadow-indigo-500/10">
            <CheckCircle className="w-8 h-8" />
          </div>
          <div>
            <h2 className="text-3xl font-black bg-clip-text text-transparent bg-gradient-to-r from-indigo-500 via-emerald-400 to-teal-400 uppercase tracking-tighter">AI Resume Analyzer</h2>
            <p className="text-slate-500 dark:text-slate-400 font-bold text-[10px] uppercase tracking-[0.2em] italic">Strict Enterprise-Grade Resume Audits</p>
          </div>
        </div>
        <button 
          onClick={onBack}
          className="px-6 py-2.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-xl font-medium transition shadow-sm"
        >
          Back to Dashboard
        </button>
      </div>

      {error && (
        <div className="bg-red-500/10 border border-red-500/30 text-red-500 p-4 rounded-xl flex items-center gap-3">
          <AlertCircle className="w-5 h-5 flex-shrink-0" />
          <p className="font-medium">{error}</p>
        </div>
      )}

      {state === 'IDLE' && (
        <div
          className="border-2 border-dashed border-slate-200 dark:border-slate-800 rounded-3xl p-12 text-center hover:border-indigo-500/50 hover:bg-indigo-500/5 transition-all cursor-pointer relative group shadow-inner"
          onDragOver={(e) => e.preventDefault()}
        >
          <input
            type="file"
            accept=".pdf,.docx,.txt"
            className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
            onChange={handleFileUpload}
          />
          <div className="w-24 h-24 bg-slate-100 dark:bg-slate-800 rounded-full flex items-center justify-center mx-auto mb-6 text-slate-400 group-hover:text-indigo-500 group-hover:scale-110 transition-transform shadow-lg">
            <Upload className="w-12 h-12" />
          </div>
          <h3 className="text-2xl font-bold mb-2 text-slate-900 dark:text-white uppercase tracking-tight">Load Professional Resume</h3>
          <p className="text-slate-500 dark:text-slate-400 mb-8 max-w-md mx-auto font-medium">
            Strict PDF/DOCX parsing for Enterprise selection standards.
          </p>
          <div className="inline-flex items-center gap-3 px-6 py-3 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl text-sm text-slate-600 dark:text-slate-300 shadow-xl">
            <RefreshCw className="w-5 h-5 text-indigo-500" />
            <span className="font-black uppercase tracking-widest text-[10px]">V1.0 High-Performance Core</span>
          </div>

          <div className="mt-12 max-w-2xl mx-auto space-y-4">
            <div className="flex items-center gap-2 text-slate-400 mb-2">
              <Briefcase className="w-4 h-4" />
              <span className="text-xs font-black uppercase tracking-widest">Required Job Context</span>
            </div>
            <textarea
              placeholder="Paste the Job Description to initialize keyword matching..."
              className="w-full h-32 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 text-sm focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none transition-all resize-none shadow-sm font-medium"
              value={jobDescription}
              onChange={(e) => setJobDescription(e.target.value)}
            />
          </div>
        </div>
      )}

      {state === 'ANALYZING' && (
        <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-16 text-center shadow-2xl">
          <div className="w-24 h-24 relative mx-auto mb-8">
            <div className="absolute inset-0 border-4 border-indigo-500/20 rounded-full animate-ping"></div>
            <div 
              className="absolute inset-0 border-4 border-indigo-500 rounded-full transition-all duration-300" 
              style={{ clipPath: `inset(0 0 0 ${100 - progress}%)` }}
            ></div>
            <Loader2 className="w-full h-full text-indigo-500 animate-spin opacity-20" />
            <div className="absolute inset-0 flex items-center justify-center font-black text-xl text-slate-900 dark:text-white">
              {progress}%
            </div>
          </div>
          <h3 className="text-2xl font-black mb-2 text-slate-900 dark:text-white uppercase tracking-tighter">Executing Audit...</h3>
          <p className="text-indigo-500 animate-pulse font-black text-sm uppercase tracking-widest">{analysisStep}</p>
          <div className="mt-12 w-full bg-slate-100 dark:bg-slate-800 rounded-full h-3 overflow-hidden">
            <div
              className="h-full bg-gradient-to-r from-indigo-500 to-emerald-500 transition-all duration-300"
              style={{ width: `${progress}%` }}
            />
          </div>
        </div>
      )}

      {state === 'RESULT' && analysis && (
        <div className="space-y-8 animate-slide-up">
           <div className="grid lg:grid-cols-12 gap-8">
            {/* Score Sidebar */}
            <div className="lg:col-span-4 space-y-6">
              <div className="bg-white dark:bg-slate-900 border-2 border-slate-100 dark:border-slate-800 rounded-[2.5rem] p-10 text-center shadow-2xl relative overflow-hidden">
                <h3 className="text-slate-400 dark:text-slate-500 font-black uppercase tracking-[0.3em] text-[10px] mb-8">Performance Score</h3>
                <div className={`w-48 h-48 rounded-full border-[12px] flex flex-col items-center justify-center mx-auto mb-8 ${getScoreColor(analysis.ats_score)} shadow-2xl shadow-current/20 relative`}>
                  <span className="text-7xl font-black tracking-tighter">{analysis.ats_score}</span>
                  <span className="text-xs font-black opacity-40 uppercase">Index</span>
                </div>
                <div className={`text-2xl font-black uppercase tracking-tight ${getScoreColor(analysis.ats_score).split(' ')[0]}`}>
                  {getScoreGrade(analysis.ats_score)}
                </div>

                <div className="mt-12 space-y-5 text-left">
                  <h4 className="text-[10px] font-black uppercase tracking-[0.2em] text-slate-400 mb-2">Technical Dimension Breakdown</h4>
                  {[
                    { label: 'Keyword Match (35%)', val: analysis.keyword_match_score, max: 35 },
                    { label: 'Skills Coverage (20%)', val: analysis.skills_score, max: 20 },
                    { label: 'Work Experience (20%)', val: analysis.experience_score, max: 20 },
                    { label: 'Education (10%)', val: analysis.education_score, max: 10 },
                    { label: 'Formatting (15%)', val: analysis.formatting_score, max: 15 }
                  ].map((item, i) => (
                    <div key={item.label} className="space-y-2">
                      <div className="flex justify-between text-[10px] font-black uppercase tracking-widest text-slate-500">
                        <span>{item.label}</span>
                        <span className="text-slate-900 dark:text-white font-black">{item.val}</span>
                      </div>
                      <div className="h-2 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-gradient-to-r from-indigo-500 to-emerald-400 transition-all duration-1000" 
                          style={{ width: `${(item.val / item.max) * 100}%`, transitionDelay: `${i * 150}ms` }}
                        />
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Formatting Issues */}
              <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-3xl p-8 shadow-xl">
                 <h3 className="font-black text-slate-900 dark:text-white text-xs uppercase tracking-widest mb-6 flex items-center gap-3">
                    <AlertCircle className="w-4 h-4 text-red-500" />
                    Formatting Violations
                 </h3>
                 <div className="space-y-3">
                    {analysis.formatting_issues.length > 0 ? (
                       analysis.formatting_issues.map((issue, i) => (
                          <div key={i} className="flex items-start gap-3 p-4 bg-red-500/5 rounded-2xl border border-red-500/10">
                             <AlertCircle className="w-4 h-4 text-red-500 mt-0.5" />
                             <span className="text-xs font-bold text-red-700 dark:text-red-400">{issue}</span>
                          </div>
                       ))
                    ) : (
                       <div className="text-center py-4 bg-emerald-500/5 rounded-2xl border border-emerald-500/10">
                          <CheckCircle className="w-6 h-6 text-emerald-500 mx-auto mb-2" />
                          <span className="text-[10px] font-black text-emerald-600 uppercase">Audit Clean</span>
                       </div>
                    )}
                 </div>
              </div>
            </div>

            {/* Main Content */}
            <div className="lg:col-span-8 space-y-8">
              {/* Keywords & Weak Sections */}
              <div className="grid md:grid-cols-2 gap-6">
                <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 shadow-xl">
                  <h3 className="font-black text-slate-900 dark:text-white text-sm uppercase tracking-widest mb-6 flex items-center gap-3">
                    <Upload className="w-5 h-5 text-indigo-500" />
                    Missing Keywords
                  </h3>
                  <div className="flex flex-wrap gap-3">
                    {analysis.missing_keywords.length > 0 ? (
                      analysis.missing_keywords.map((kw, i) => (
                        <span key={i} className="px-4 py-2 bg-slate-50 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700 rounded-xl text-[10px] font-black uppercase tracking-wider">
                          {kw}
                        </span>
                      ))
                    ) : (
                      <p className="text-emerald-500 text-xs font-black uppercase tracking-widest italic">All required target keywords identified.</p>
                    )}
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 shadow-xl">
                  <h3 className="font-black text-slate-900 dark:text-white text-sm uppercase tracking-widest mb-6 flex items-center gap-3">
                    <X className="w-5 h-5 text-red-500" />
                    Weak Sections
                  </h3>
                  <div className="space-y-3">
                    {analysis.weak_sections.length > 0 ? (
                      analysis.weak_sections.map((section, i) => (
                        <div key={i} className="flex items-center gap-3 p-3 bg-red-500/5 rounded-xl border border-red-500/10">
                           <AlertCircle className="w-4 h-4 text-red-500" />
                           <span className="text-[10px] font-bold text-red-600 uppercase">{section}</span>
                        </div>
                      ))
                    ) : (
                      <p className="text-emerald-500 text-xs font-black uppercase tracking-widest italic text-center py-4">High structural integrity.</p>
                    )}
                  </div>
                </div>
              </div>

              {/* Improved Bullet Points */}
              <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 shadow-xl">
                <h3 className="font-black text-slate-900 dark:text-white text-sm uppercase tracking-widest mb-6 flex items-center gap-3">
                  <RefreshCw className="w-5 h-5 text-emerald-500" />
                  High-Impact Achievements (Improved)
                </h3>
                <div className="grid gap-4">
                  {analysis.improved_bullet_points.map((bp, i) => (
                    <div key={i} className="bg-emerald-500/5 p-6 rounded-3xl border border-emerald-500/10 group transition-all hover:bg-emerald-500/10">
                      <div className="flex items-start gap-4">
                        <div className="w-8 h-8 rounded-xl bg-emerald-500 text-white flex items-center justify-center font-black text-xs flex-shrink-0 group-hover:scale-110 transition-transform">
                          {i + 1}
                        </div>
                        <p className="text-sm text-slate-700 dark:text-slate-200 leading-relaxed font-bold">
                          {bp}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Expert Suggestions */}
              <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-[2.5rem] p-8 shadow-xl">
                <h3 className="font-black text-slate-900 dark:text-white text-sm uppercase tracking-widest mb-6 flex items-center gap-3">
                  <Lightbulb className="w-5 h-5 text-yellow-500" />
                  Strategy & Optimization
                </h3>
                <div className="grid sm:grid-cols-2 gap-4">
                  {analysis.suggestions.map((suggestion, j) => (
                    <div key={j} className="bg-slate-50 dark:bg-slate-800/50 p-6 rounded-3xl border border-slate-100 dark:border-slate-700 group hover:border-indigo-500/30 transition-all">
                       <span className="text-xs leading-relaxed text-slate-600 dark:text-slate-300 font-bold">{suggestion}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 pt-4">
                <button
                  onClick={() => setState('IDLE')}
                  className="flex-1 py-5 bg-white dark:bg-slate-800 hover:bg-slate-50 dark:hover:bg-slate-700 border border-slate-200 dark:border-slate-700 rounded-2xl font-black text-slate-700 dark:text-slate-200 transition shadow-lg flex items-center justify-center gap-3 uppercase tracking-widest text-[10px]"
                >
                  <RefreshCw className="w-4 h-4" /> Reset Audit
                </button>
                <button
                  onClick={handleDownload}
                  className="flex-1 py-5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-2xl font-black transition-all shadow-xl shadow-indigo-600/20 flex items-center justify-center gap-3 uppercase tracking-widest text-[10px]"
                >
                  Download Engine Audit Report <RefreshCw className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ResumeAnalyzer;
